//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63133655.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NDXUATKHO
    {
        public string SoPhieuXuat { get; set; }
        public string MaCF { get; set; }
        public string LoaiCF { get; set; }
        public Nullable<short> SoLuong { get; set; }
        public string DVT { get; set; }
    
        public virtual THEKHO THEKHO { get; set; }
        public virtual XUATKHO XUATKHO { get; set; }
    }
}
