//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63133655.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEKHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THEKHO()
        {
            this.NDNHAPKHO = new HashSet<NDNHAPKHO>();
            this.NDXUATKHO = new HashSet<NDXUATKHO>();
        }
    
        public string MaCF { get; set; }
        public string LoaiCF { get; set; }
        public Nullable<short> SoLuong { get; set; }
        public string DVT { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NDNHAPKHO> NDNHAPKHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NDXUATKHO> NDXUATKHO { get; set; }
    }
}
